### ISSUE TITLE
Remove wildcard imports 🍷 🥇 

### ISSUE THREAD

**Issue by oas004** [oas004/Material3Playground#6]
Currently we have some wildcard imports in the project. Would be nice to remove these 🛩️ 😄 

I think this was my bad, when initialising the project and moving the code, the IDE added them automatically since I had not removed that option.

**Comment by rubenquadros** [comment]
Hey @oas004, I can give this a go!

**Comment by rubenquadros** [comment]
Hey @oas004 I couldn't find any wildcard imports. There were some unused imports in `Chips.kt` but other than that everything looks good!

**Comment by oas004** [comment]
> Hey @oas004 I couldn't find any wildcard imports. There are some unused imports in `Chips.kt` but other than that everything looks good!

Oh okay, sorry about that. I think we can probably close this issue then :) Thank you for looking into it :) You can remove the unused import in `Chips.kt` if you want the hacktober contribution :)

**Comment by rubenquadros** [comment]
Thanks very kind of you, thanks! I can contribute to #27 as well!

**Comment by oas004** [comment]
No worries! Feel free to take a look at that if you want to! :)
