### ISSUE TITLE
No .dmg files available for releases after 1.0.0

### ISSUE THREAD

**Issue by sebastianharder** [oas004/Material3Playground#83]
The readme mentions that .dmg files can be found in the release pages. However, only release 1.0.0 contains a .dmg file in the assets section.

**Comment by oas004** [comment]
Yes you are right, and sorry that is my fault when releasing. I think I had some issues signing the `.dmg`s with a app id, so they did not provide much value. However, I think I can remove the line in the readme stating that we are shipping the `.dmg` file. I will fix this. Thanks for reporting :)
